### ISSUE TITLE
Dutch Decisions

### ISSUE THREAD

**Issue by NekMC** [JmanThunder/The-Grand-Combo#116]
This may be a minor problem but whatever, the problem is that some decisions of the Netherlands ask you for the invention "The Dark Continent"(some of them are, "The end of the Javanese Sultanates, The Short Declaration) which, as far as I know, it's not included into the inventions list of the mod, and actually some Scramble for Africa events may need The Dark Continent or other nations may need the invention in order to activate any decision related to Colonialism, so I will be glad If somebody can fix this error, Thank you and blessings.

**Comment by LouisTheFly** [comment]
Hiya, thanks for your report, the dark continent invention can be found under Revolution and Counter-Revolution in culture tech (you have to scroll down to see it and it has very specific requirements to fire). I believe it has moved location from other mods but from what I can see its still there. If its not showing up for you ill look into it further.

**Comment by rderekp** [comment]
This invention was accidentally left out of the Master Build, but it's been fixed in the Dev Build.
