### ISSUE TITLE
Establish Protectorate Casus Belli uses region adjective 

### ISSUE THREAD

**Issue by LouisTheFly** [JmanThunder/The-Grand-Combo#159]
e.g. 'aquire british sudanese'

**Comment by anzu-3278** [comment]
![image](https://user-images.githubusercontent.com/66275036/87366015-f32fd600-c577-11ea-9bdb-66dd00b6b191.png) Fixed with commit https://github.com/JmanThunder/The-Grand-Combo/commit/61509cbbea600d58fd3ab15a65ede26ee4a4612d
