### ISSUE TITLE
Two Unify Italy decisions are available

### ISSUE THREAD

**Issue by anzu-3278** [JmanThunder/The-Grand-Combo#166]
Both do the same thing, just one costs infamy while the other doesn't.

**Comment by LouisTheFly** [comment]
anzu do you know the event /decision ids for these italian issues?

**Comment by anzu-3278** [comment]
I know, I am working on it now.

**Comment by anzu-3278** [comment]
Fix in https://github.com/JmanThunder/The-Grand-Combo/pull/180
