### ISSUE TITLE
Transfer of Commits from My Fork

### ISSUE THREAD

**Issue by vjwua** [JmanThunder/The-Grand-Combo#5]
It is enough to transfer my work to yours. They include:
- **Fixed borders** at the Netherlands, Switzerland, Italy, India and South Africa
- **Historically** correct flags (at 1836)
- Few **new** countries at Indonesia 

and some minor things. What do you think?

**Comment by JmanThunder** [comment]
These are good and can be implemented.

**Comment by vjwua** [comment]
if not already implemented ...

**Comment by DrFaustie** [comment]
@vjwua make a pull request

**Comment by DrFaustie** [comment]
Merged
